### PR TITLE
Added .NET Core Compatibility

### PR DESCRIPTION
**Pull request by adword16**
Maybe you want net Core Compatibility

### CODE REVIEW

**Comment by VladimirAkopyan** [comment]
!! Good job!

**Comment by adword16** [comment]
Don't mention it.
Are you going to merge it?

**Comment by VladimirAkopyan** [comment]
I don't own the repo, i am just a random dude

**Comment by VladimirAkopyan** [comment]
I opted for supporting .Net Standard 2.0, f69cd78aaab83fbadf342236ddecc7abe5cea760 
This will allow supporting all platforms .Net core, Xamarin, UWP, etc. Also reduces the number of #ifdefs.

**Comment by dtflx01** [comment]
@VladimirAkopyan , take care for Windows CE, the compact framework is restricted and use of defines COMPACT_FRAMEWORK are often mandatories.
Regards

**Pull request closed without merging**
