### PR TITLE
Update MqttSubscriberManager.cs

### PR DESCRIPTION
**Pull request by GioviQ**
see https://github.com/ppatierno/gnatmq/issues/13

### CODE REVIEW

**Comment by jepickett-mm** [comment]
It has been more than a year since these pull requests have been submitted. They fix problems that crash the broker when under stress, Please review and accept.

**Comment by GioviQ** [comment]
I just updated my fork https://github.com/GioviQ/gnatmq
with this pull request and other improvements to fix https://github.com/ppatierno/gnatmq/issues/36

**Comment by VladimirAkopyan** [comment]
OK, we now have the power to merge this in, should we just go ahead?

**Comment by dtflx01** [comment]
ppatierno#13 is OK, you can merge it.

**Comment by ppatierno** [comment]
I'm going to merge ;)

**Comment by dtflx01** [comment]
This issue is still persistent, see #52.

**Pull request merged**
